"""
Django settings for kino_mart_backend project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads .env for local development. In production (Render) there is no .env
# file — real values are set as environment variables in the dashboard, and
# this call is a harmless no-op.
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# --- Core / security ---
# SECURITY WARNING: keep the secret key used in production secret!
# No hardcoded fallback in production — if SECRET_KEY isn't set, fail loudly
# rather than silently running with a known/insecure key.
DEBUG = env_bool('DJANGO_DEBUG', False)
SECRET_KEY = os.environ.get('SECRET_KEY') or (
    'django-insecure-dev-only-key-CHANGE-ME' if DEBUG else None
)
if not SECRET_KEY:
    raise RuntimeError('SECRET_KEY environment variable is required when DJANGO_DEBUG=False')

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'storages',
    'catalog',
    'storefront',
    'accounts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if DEBUG:
    # Prints per-request timing/query-count to the runserver console — local
    # dev diagnostics only, never added in production.
    MIDDLEWARE.append('kino_mart_backend.timing_middleware.RequestTimingMiddleware')

ROOT_URLCONF = 'kino_mart_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kino_mart_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# This project always uses the Postgres DB at DATABASE_URL (Neon) — no sqlite
# fallback. Set DATABASE_URL in .env locally and in the Render dashboard for
# production; both point at the same database unless you deliberately change it.

DATABASE_URL = os.environ.get('DATABASE_URL')
if not DATABASE_URL:
    raise RuntimeError(
        'DATABASE_URL environment variable is required (Postgres/Neon connection string).'
    )

DATABASES = {
    'default': dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://localhost:4173')
# Never leave this True in production — it defeats CORS_ALLOWED_ORIGINS entirely.
CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', DEBUG)

# --- Media storage: Cloudflare R2 (S3-compatible) — always, no local-disk fallback ---
# Same pattern as DATABASE_URL: these are required env vars, set in .env locally
# and in the Render dashboard for production, both pointing at the same bucket.
STORAGES['default'] = {'BACKEND': 'storages.backends.s3.S3Storage'}

AWS_ACCESS_KEY_ID = os.environ.get('R2_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('R2_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = os.environ.get('R2_ENDPOINT_URL')

if not all([AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_STORAGE_BUCKET_NAME, AWS_S3_ENDPOINT_URL]):
    raise RuntimeError(
        'R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_BUCKET_NAME and R2_ENDPOINT_URL '
        'are all required (Cloudflare R2 is the only media storage backend).'
    )

AWS_S3_REGION_NAME = 'auto'
AWS_S3_ADDRESSING_STYLE = 'virtual'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False  # public bucket — no need for signed URLs

# Optional: serve media through your own R2 public/custom domain
# (e.g. images.kinomart.com, or the bucket's r2.dev URL) instead of the raw
# S3 endpoint. Set R2_PUBLIC_DOMAIN to enable this.
R2_PUBLIC_DOMAIN = os.environ.get('R2_PUBLIC_DOMAIN')
if R2_PUBLIC_DOMAIN:
    AWS_S3_CUSTOM_DOMAIN = R2_PUBLIC_DOMAIN
    MEDIA_URL = f'https://{R2_PUBLIC_DOMAIN}/'
else:
    MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/'



CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://localhost:8000,http://127.0.0.1:8000',
)
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# --- HTTPS / HSTS (Render terminates TLS and forwards via X-Forwarded-Proto) ---
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 1 week to start; raise once confident
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    # JWTAuthentication only *identifies* the user when a valid Bearer token is sent;
    # it doesn't lock anything down by itself. DEFAULT_PERMISSION_CLASSES stays
    # AllowAny so existing public endpoints (products, checkout, etc.) keep working
    # for guests. Views that need a logged-in user (wishlist, cart, /orders/mine/,
    # /auth/me/) set permission_classes=[IsAuthenticated] explicitly.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# --- SSLCommerz (online payments: cards, bKash, Nagad, Rocket, internet banking) ---
# Sandbox defaults below are SSLCommerz's public demo store credentials (store_id
# "testbox" / password "qwerty") — they work out of the box against
# sandbox.sslcommerz.com with no signup, which is why they're safe to leave as
# literal defaults here rather than requiring a .env entry to run at all.
# For production: register a live store at https://signup.sslcommerz.com/register,
# then set SSLCOMMERZ_STORE_ID / SSLCOMMERZ_STORE_PASSWORD / SSLCOMMERZ_SANDBOX=False
# as real environment variables — never commit live credentials to this file.
SSLCOMMERZ_STORE_ID = os.environ.get('SSLCOMMERZ_STORE_ID', 'testbox')
SSLCOMMERZ_STORE_PASSWORD = os.environ.get('SSLCOMMERZ_STORE_PASSWORD', 'qwerty')
SSLCOMMERZ_SANDBOX = os.environ.get('SSLCOMMERZ_SANDBOX', 'True') == 'True'

# Used to build the absolute callback URLs SSLCommerz redirects/posts to, and to
# send the customer back to the right frontend origin once payment is done.
BACKEND_URL = os.environ.get('BACKEND_URL', 'http://localhost:8000')
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')
