# Generated by Django 5.2.13 on 2026-07-30 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Set once an online payment is confirmed by SSLCommerz. Always False for COD.'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('online', 'Online payment')], default='cod', max_length=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('valid', 'Valid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='initiated', max_length=20)),
                ('method', models.CharField(blank=True, help_text="Channel used, as reported by SSLCommerz, e.g. 'bKash', 'Nagad', 'VISA-Brac bank'.", max_length=100)),
                ('val_id', models.CharField(blank=True, max_length=100)),
                ('bank_tran_id', models.CharField(blank=True, max_length=100)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='storefront.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
